package View;

import Interfaces.Windows;
import Model.User;
import java.util.Enumeration;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

public class UserViewGUI extends javax.swing.JFrame implements Windows {

    private MiniTwitterGUI FrameA;
    
    private User user;
    DefaultListModel followings;
    DefaultListModel newsFeed;
    /**
     * Creates new form UserViewGUI
     */
    public UserViewGUI(User currentUser) {
        this.user = currentUser;
        this.followings = new DefaultListModel();
        this.newsFeed = new DefaultListModel();
        
        initComponents();
    }
    
    public void setFrame(MiniTwitterGUI FrameA) {
        this.FrameA = FrameA;
    }
    
    public void PopUpMessage(String message, int messageType){
          JOptionPane.showMessageDialog(null, message, "Alert", messageType);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userID = new javax.swing.JTextArea();
        postTweet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentFollowingJList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TweetMessage = new javax.swing.JTextArea();
        followUser = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        newsFeedJList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        userID.setColumns(10);
        userID.setRows(5);
        jScrollPane1.setViewportView(userID);

        postTweet.setText("POST TWEET");
        postTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postTweetActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(currentFollowingJList);
        currentFollowingJList.setModel(followings);

        TweetMessage.setColumns(10);
        TweetMessage.setRows(5);
        jScrollPane3.setViewportView(TweetMessage);

        followUser.setText("FOLLOW USER");
        followUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followUserActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(newsFeedJList);
        newsFeedJList.setModel(newsFeed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(followUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(postTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(followUser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(postTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void followUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followUserActionPerformed
        
        //check if user exists
        User tryingtoFollow = TraverseJTree(userID.getText());
        
        if(tryingtoFollow == null){
            PopUpMessage("User does not exist OR You can't follow yourself", JOptionPane.WARNING_MESSAGE);
        }
        else if (!user.Follow(tryingtoFollow)){
            updateFollowingList(tryingtoFollow);
            tryingtoFollow.beFollowed(user);
        }
        else{
            PopUpMessage("You are already following this user", JOptionPane.WARNING_MESSAGE);
        }
        
        System.out.println("User: " + user.getUniqueID());
        System.out.println("Followings" + user.getFollowings().getListFollowings());
        System.out.println("Followers" + user.getFollowers().getListFollowers());
                
        
    }//GEN-LAST:event_followUserActionPerformed

    private void postTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postTweetActionPerformed
        user.tweet(TweetMessage.getText());
        UpdateNewsFeedList(user.getLastTweet());
        UpdateEveryonesGUI();
    }//GEN-LAST:event_postTweetActionPerformed

    @Override
    public void display() {
        
        followings.clear();
        newsFeed.clear();
        followings.addElement("Followings");
        newsFeed.addElement("NewsFeed");
        initialUpdateFollowings();
        initialUpdateNewsFeed();
        
        this.setTitle(user.toString());
        this.setVisible(true);
    }
    
    public void updateFollowingList(User newFollowing){
        followings.addElement(newFollowing);
    }
    
    public void initialUpdateFollowings(){
        
        List<User> currentFollowings = user.getFollowings().getListFollowings();
        
        for(User each: currentFollowings){
            followings.addElement(each);
        }
    }
    
    public void UpdateNewsFeedList(String newNews){
        newsFeed.addElement(newNews);
    }
    
    public void initialUpdateNewsFeed(){ 
        
         List<String> currentNewsFeed = user.getNewsfeed().getNews();
        
        for(String each: currentNewsFeed){
            this.newsFeed.addElement(each);
        }
    }
    public void  UpdateEveryonesGUI(){
        
        List<User> currentFollowers = user.getFollowers().getListFollowers();
        
        for (UserViewGUI value : FrameA.users.values()) {
            
            if(!value.equals(this) || currentFollowers.contains(value.user)){
                value.UpdateNewsFeedList(value.user.getLastTweet());
            }
        }
    }
    
    public User TraverseJTree(String userName){
        
        Enumeration en = FrameA.root.depthFirstEnumeration();
        while (en.hasMoreElements()) {
            
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) en.nextElement();

            if(node.getUserObject() instanceof User){
               User currentUser = (User) node.getUserObject();
               
                if(currentUser.getUniqueID().equals(userName) && !currentUser.getUniqueID().equals(user.getUniqueID())){
                    return currentUser;
                }
            }

        }
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TweetMessage;
    private javax.swing.JList<String> currentFollowingJList;
    private javax.swing.JButton followUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> newsFeedJList;
    private javax.swing.JButton postTweet;
    private javax.swing.JTextArea userID;
    // End of variables declaration//GEN-END:variables
}
